name: Continuous Deployment
on:
  workflow_run:
    workflows: [Continuous Integration]
    types: [completed]
    branches: [main]
jobs:
  on-success:
    name: Semantic Release
    uses: cncsc/actions/.github/workflows/semantic-release.yaml@main
    secrets:
      GIT_TOKEN_BASIC: ${{ secrets.GIT_TOKEN_BASIC }}
      NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
