name: Continuous Delivery
on:
  workflow_run:
    workflows: [Continuous Integration]
    types: [completed]
    branches: [main]
jobs:
  on-success:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > .npmrc
      - run: npx semantic-release --dry-run false --ci false
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN_BASIC }}
